version: "3.9"

services:
  db:
    image: postgres:16.2
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=jem
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=jemdb
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./scripts/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: jem
    restart: always
    ports:
      - "8002:8002"
    depends_on:
      - db
    volumes:
      - .:/app
    command: bash -c "uvicorn src.main:app --reload --workers 1 --host 0.0.0.0 --port 8002"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db