version: "3.9"

services:
  app:
    build: .
    container_name: jem
    restart: always
    ports:
      - "8002:8002"
    volumes:
      - .:/app
    command: bash -c "uvicorn src.main:app --reload --workers 1 --host 0.0.0.0 --port 8002"