version: "3.9"

services:
  db:
    image: postgres:16.2
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=jem
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=jem
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  app:
    build: .
    container_name: jem
    restart: always
    ports:
      - "8002:8002"
    depends_on:
      - db
    volumes:
      - .:/app
    command: uvicorn src.main:app --reload --workers 1 --host 0.0.0.0 --port 8002